Task table - actually create a task table from scratch!
lindsayplatt/ds-pipelines-3 pull request #5
Opened 2020-06-29 21:30 UTC by lindsayplatt

Two things that came up at the end of this that I am no sure about:

1. The instructions that say `add it to the (new) depends field for the state_tasks target` when referring to where you add `parameter` confuse me. Is it talking about the `...` we just added or how you can use `depends:` as another field with the target `state_tasks`?

2. I am surprised by the following policy - I did not know that was what we were supposed to do and none of the pipelines I've been working on have been doing that. I suppose we should now!

> our current team policy is to usually commit these auto-generated YAML files, with optional exceptions for really large task tables.

2020-06-29 23:35 UTC, aappling-usgs commented
> The instructions that say add it to the (new) depends field for the state_tasks target when referring to where you add parameter confuse me. Is it talking about the ... we just added or how you can use depends: as another field with the target state_tasks?

You actually should add
```
depends: parameter
```
to the `state_tasks` target and take that argument out of the call to `state_tasks`. The reason for this separation of code files (get passed as arguments to `state tasks`) and parameters (get declared as `depends`) will become clearer in an issue or two as we keep modifying the current code.


> I am surprised by the following policy - I did not know that was what we were supposed to do and none of the pipelines I've been working on have been doing that. I suppose we should now!

>> our current team policy is to usually commit these auto-generated YAML files, with optional exceptions for really large task tables.

Hah - good point. My statement may be more proscriptive rather than descriptive - I agree that we don't often do this now, but recently Jordan and I (and Sam, I think?) have had discussions where we've agreed that it could be useful to commit these more often. But then again, we often have really large task tables, in which case we pretty quickly go back to not committing these.

2020-06-29 23:39 UTC, aappling-usgs requested changes
Just looked through your code - it's all spot on, except please do move `parameter` into a `depends` of `state_tasks`.

2020-06-30 11:45 UTC, jordansread reviewed
small request to add the `depends: parameter` noted in Alison's review

2020-06-30 12:47 UTC, lindsayplatt commented
Done but just a note for maybe a future course improvement - I don't think that `depends` was talked about much leading up to this part (other than its use in the overall target), so it may need a small section before asking for it to be used. The timing was also a little confusing with it being around the time we learned to pass dependencies in with `...`

2020-06-30 12:50 UTC, lindsayplatt commented
@aappling-usgs I'd love to hear a bit more about motivation for committing smaller auto-generated task makefiles. Just yesterday morning (before I saw this), I changed code in `vizstorm-GIF` to auto-generate a makefile for the "outro" frames and not commit that file. It isn't a big makefile, so it sounds like it might make sense to still commit.

2020-06-30 13:22 UTC, aappling-usgs approved these changes

2020-06-30 13:31 UTC, merged

2020-06-30 13:37 UTC, aappling-usgs commented
@lindsayplatt There's definitely room for developer discretion on this decision about whether to commit a task remakefile, but recently there have been a handful of times when I/we made modifications that affected a task remakefile, or wanted to debug issues with those task remakefiles across team members, and it was or would have been handy to have a record of what changed and how the task remakefile looked at the time. For example, for one of the water temperature repos, having that file git committed would have made it easier to discover that we had two versions of scipiper running on different machines, with implications (across those particular versions) for the contents of the task makefile even though the code was the same. And when I'm new to a repo that others have already worked on, I often find it useful to look through all the remake files, including any task remake files, to get my bearings. Yet another (but rarer) use case is this course, where it's easier to review each learner's task table code alongside the produced task table just to double check that the task table code does what is intended. Lastly, the cost is low for small task makefiles, so the decision to commit them more often partly comes down to "why not?".

So that's our reasoning for proposing a shift toward committing those files more often. If any of those potential uses resonate with you for the vizstorm gif, I say go for it. But you also needn't feel guilty for deciding in the other direction (not to commit) if you think it'd just be a pain for some reason.